#!/usr/bin/env bash
# iDeer Intranet Deployment Pre-check
# Validates that all prerequisites for intranet deployment are met.
# Run from the bundle root, next to ideer-images-*.tar / env.intranet.

set -euo pipefail

ERRORS=0
WARNINGS=0

echo "=== iDeer Intranet Deployment Pre-check ==="
echo ""

# 1. Check Docker is available
echo -n "[1/8] Docker... "
if command -v docker &>/dev/null; then
    echo "OK ($(docker --version | head -1))"
else
    echo "MISSING"; ((ERRORS += 1))
fi

# 2. Check Docker Compose is available
echo -n "[2/8] Docker Compose... "
if docker compose version &>/dev/null 2>&1; then
    echo "OK"
else
    echo "MISSING"; ((ERRORS += 1))
fi

# 3. Check required Docker images are loaded
#    Version comes from the bundle tar name (ideer-images-<VERSION>.tar),
#    matching how deploy-intranet.sh derives $VERSION.
IMAGES_TAR="$(find . -maxdepth 1 -name 'ideer-images-*.tar' 2>/dev/null | head -1 || true)"
if [ -n "$IMAGES_TAR" ]; then
    VERSION="$(basename "$IMAGES_TAR" | sed -E 's/^ideer-images-(.*)\.tar$/\1/')"
else
    VERSION="latest"
fi
echo "[3/8] Docker images (version $VERSION)..."
REQUIRED_IMAGES=("ideer-frontend:$VERSION" "ideer-gateway:$VERSION" "nginx:alpine")
for img in "${REQUIRED_IMAGES[@]}"; do
    echo -n "  - $img... "
    if docker image inspect "$img" &>/dev/null; then
        echo "OK"
    else
        echo "MISSING"; ((WARNINGS += 1))
    fi
done

# 4. Check config.intranet.yaml exists
echo -n "[4/8] config.intranet.yaml... "
if [ -f "config.intranet.yaml" ]; then
    echo "OK"
else
    echo "MISSING (copy from config.intranet.yaml.example and customize)"; ((ERRORS += 1))
fi

# 5. Check env.intranet exists (generated by ./deploy-intranet.sh prepare)
echo -n "[5/8] env.intranet... "
if [ -f "env.intranet" ]; then
    echo "OK"
else
    echo "MISSING (run ./deploy-intranet.sh prepare to generate it)"; ((WARNINGS += 1))
fi

# 6. Check LLM endpoint is reachable (if configured)
echo -n "[6/8] LLM endpoint... "
if [ -n "${IDEER_LLM_ENDPOINT:-}" ]; then
    if curl -s --connect-timeout 3 "${IDEER_LLM_ENDPOINT}/models" >/dev/null 2>&1 || \
       curl -s --connect-timeout 3 "${IDEER_LLM_ENDPOINT}/v1/models" >/dev/null 2>&1; then
        echo "OK ($IDEER_LLM_ENDPOINT)"
    else
        echo "UNREACHABLE ($IDEER_LLM_ENDPOINT)"; ((WARNINGS += 1))
    fi
else
    echo "SKIPPED (set IDEER_LLM_ENDPOINT to check)"
fi

# 7. Check the deployment port is available (PORT from env.intranet, default 2026)
echo "[7/8] Port availability..."
PORT="${PORT:-2026}"
if [ -f "env.intranet" ]; then
    ENV_PORT="$(grep -E '^PORT=' env.intranet | tail -1 | cut -d= -f2 || true)"
    [ -n "$ENV_PORT" ] && PORT="$ENV_PORT"
fi
echo -n "  - Port $PORT (PORT)... "
if ss -tlnp 2>/dev/null | grep -q ":${PORT} " || netstat -tlnp 2>/dev/null | grep -q ":${PORT} "; then
    echo "IN USE"; ((WARNINGS += 1))
else
    echo "OK"
fi

# 8. Check disk space
echo -n "[8/8] Disk space... "
AVAILABLE_GB=$(df -BG . | tail -1 | awk '{print $4}' | sed 's/G//')
if [ "$AVAILABLE_GB" -ge 10 ]; then
    echo "OK (${AVAILABLE_GB}GB available)"
else
    echo "LOW (${AVAILABLE_GB}GB available, recommend 10GB+)"; ((WARNINGS += 1))
fi

echo ""
echo "=== Results ==="
echo "Errors: $ERRORS"
echo "Warnings: $WARNINGS"

if [ "$ERRORS" -gt 0 ]; then
    echo "FAILED: Please fix the errors above before deploying."
    exit 1
else
    echo "PASSED: Ready for intranet deployment."
    exit 0
fi
